schedules:
- cron: "*/5 * * * *"
  displayName: Every 5 minutes
  branches:
    include:
    - main

pool:
  name: Default

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Dummy task to force pipeline execution"
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Agrega aquí tu script de PowerShell
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JAVA_HOME'
    jdkUserInputPath: '/Library/Java/JavaVirtualMachines/jdk-11.0.16.1.jdk/Contents/Home'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    arguments: '--configuration $(buildConfiguration)'
    tasks: 'clean build -x test'
- task: CmdLine@2
  inputs:
    arguments: '--configuration $(buildConfiguration)'
    script: 'gradle clean test aggregate'
